databases:
  - name: escaperoomdb
    plan: free
    databaseName: escaperoom
    user: escaperoom

services:
  - type: web
    plan: free
    name: escaperoom
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python3 -m gunicorn escaperoom.asgi:application -k uvicorn.workers.UvicornWorker"    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: escaperoomdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4