# Generated by Django 4.2.4 on 2023-12-15 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_room_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='room',
        ),
        migrations.AddField(
            model_name='photo',
            name='puzzle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.puzzle'),
        ),
    ]
