# Generated by Django 4.2.4 on 2023-12-15 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_photo_room_photo_puzzle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzle',
            name='difficulty',
            field=models.IntegerField(),
        ),
    ]
